var res = {
    MainScene_json : "res/MainScene.json",
    asd_png:"res/ASD.png",
    game_start:"res/gamestart.png",
    map:"res/map.png",
    flag_png:"res/mapview/flag.png",
    playview_png:"res/playScene/playview.png",
    enemy1_plist:"res/playScene/enemy1/enemy1.plist",
    enemy1_png:"res/playScene/enemy1/enemy1.png",
    land_png:"res/playScene/touch/land.png",
    explosion_png:"res/playScene/touch/explosion.png",
    thunder_png:"res/playScene/touch/thunder.png",
    magic_png:"res/playScene/touch/magic.png",
    magichouse_png:"res/playScene/touch/magichouse.png",
    magicbullet_png:"res/playScene/touch/maigicbullet.png",
    heart_png:"res/playScene/heart.png",
    ee_plist:"res/playScene/touch/ee.plist",
    ee_png:"res/playScene/touch/ee.png",
    ert_plist:"res/playScene/touch/ert.plist",
    ert_png:"res/playScene/touch/ert.png",
    board_png:"res/playScene/touch/Board/board.png",
    restart_png:"res/playScene/touch/Board/restart.png",
    QUIT_png:"res/playScene/touch/Board/QUIT.png",
    KillMonster:"res/playScene/touch/Board/killMonster.png",
    Monster2_png:"res/playScene/enemy2/Monster2.png",
    Monster2_plist:"res/playScene/enemy2/Monster2.plist",
    Greenarrow_png:"res/playScene/touch/Greenarrow.png",
    Underground_Prep_mp3:'res/Music/Underground_Prep.mp3',
    Map_Theme_mp3:'res/Music/Map_Theme.mp3',
    archmage_explosion_mp3:'res/Music/archmage_explosion.mp3',
    explosion_mp3:'res/Music/explosion.mp3',
    desertMap_png:"res/playScene2/bgLayer/desertMap.png",
    Floor_png:"res/playScene2/SpriteLayer/Sprite/Floor.png",
    Monster1_plist:"res/playScene2/SpriteLayer/Sprite/Monster1.plist",
    Monster1_png:"res/playScene2/SpriteLayer/Sprite/Monster1.png",
    dragon_plist:"res/playScene2/SpriteLayer/Sprite/dragon.plist",
    dragon_png:"res/playScene2/SpriteLayer/Sprite/dragon.png",
    purpleHouse_png:"res/playScene2/bgLayer/purpleHouse.png",
    purpleColumn_png:"res/playScene2/bgLayer/purplecolumn.png",
    fe_png:"res/playScene2/SpriteLayer/Sprite/fe.png",
    fe_plist:"res/playScene2/SpriteLayer/Sprite/fe.plist",
    coin_png:"res/playScene2/SpriteLayer/Sprite/coin.png",
    CanibalZombie_plist:"res/playScene2/SpriteLayer/Sprite/CanibalZombie.plist",
    CanibalZombie_png:"res/playScene2/SpriteLayer/Sprite/CanibalZombie.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
